version: '3'

services:
  mongodb-service:
    ports:
      - "8003:27017"
    volumes:
      - /var/mongodb_home
    image: "mongo"

  gitlab-service:
    ports:
      - "8002:80"
      - "8022:22"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    image: "gitlab/gitlab-ce:latest"
    
  jenkins-service:
    ports:
      - "8001:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home
    image: "jenkinsci/jenkins"

  sonarqube-service:
    ports:
      - "8004:9000"
      - "9092:9092"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /opt/sonarqube/conf
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions
      - /opt/sonarqube/lib/bundled-plugins
    image: "sonarqube"
     
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /var/lib/postgresql
      - /var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
